[2023-09-25 17:08:53,029] ERROR log_exception() L1449 Exception on /:id [DELETE] - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\flask\app.py", line 1520, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\flask\app.py", line 1539, in finalize_request
    response = self.make_response(rv)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\flask\app.py", line 1730, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a Response.
[2023-09-25 17:08:53,034] INFO _log() L224  127.0.0.1 - - [25/Sep/2023 17:08:53] "[35m[1mDELETE /:id?id=2 HTTP/1.1[0m" 500 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 17:11:49,949] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5001
 * Running on http://192.168.15.8:5001 (Press CTRL+C to quit) - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 17:11:56,661] WARNING del_list() L124  Erro ao deletar produto #'2', Lista não encontrado na base - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\list_api\app.py L124 
[2023-09-25 17:11:56,662] INFO _log() L224  127.0.0.1 - - [25/Sep/2023 17:11:56] "[33mDELETE /:id?id=2 HTTP/1.1[0m" 404 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 17:12:19,107] INFO _log() L224  127.0.0.1 - - [25/Sep/2023 17:12:19] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 17:12:21,053] INFO _log() L224  127.0.0.1 - - [25/Sep/2023 17:12:21] "POST / HTTP/1.1" 200 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 17:12:28,689] ERROR log_exception() L1449 Exception on /:id [DELETE] - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\flask\app.py", line 1520, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\flask\app.py", line 1539, in finalize_request
    response = self.make_response(rv)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\flask\app.py", line 1730, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a Response.
[2023-09-25 17:12:28,691] INFO _log() L224  127.0.0.1 - - [25/Sep/2023 17:12:28] "[35m[1mDELETE /:id?id=2 HTTP/1.1[0m" 500 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 17:12:34,129] INFO _log() L224  127.0.0.1 - - [25/Sep/2023 17:12:34] "POST / HTTP/1.1" 200 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 17:13:27,048] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5001
 * Running on http://192.168.15.8:5001 (Press CTRL+C to quit) - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 17:13:30,728] INFO _log() L224  127.0.0.1 - - [25/Sep/2023 17:13:30] "DELETE /:id?id=2 HTTP/1.1" 200 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 17:15:33,208] INFO _log() L224  127.0.0.1 - - [25/Sep/2023 17:15:33] "POST / HTTP/1.1" 200 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 17:15:40,363] INFO _log() L224  127.0.0.1 - - [25/Sep/2023 17:15:40] "DELETE /:id?id=2 HTTP/1.1" 200 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 17:15:45,164] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5001
 * Running on http://192.168.15.8:5001 (Press CTRL+C to quit) - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 17:15:48,441] INFO _log() L224  127.0.0.1 - - [25/Sep/2023 17:15:48] "POST / HTTP/1.1" 200 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 17:15:52,350] INFO _log() L224  127.0.0.1 - - [25/Sep/2023 17:15:52] "DELETE /:id?id=2 HTTP/1.1" 200 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 17:16:01,178] INFO _log() L224  127.0.0.1 - - [25/Sep/2023 17:16:01] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 17:16:01,463] INFO _log() L224  127.0.0.1 - - [25/Sep/2023 17:16:01] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 17:16:01,519] INFO _log() L224  127.0.0.1 - - [25/Sep/2023 17:16:01] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 17:16:01,519] INFO _log() L224  127.0.0.1 - - [25/Sep/2023 17:16:01] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 17:16:01,675] INFO _log() L224  127.0.0.1 - - [25/Sep/2023 17:16:01] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 17:16:01,985] INFO _log() L224  127.0.0.1 - - [25/Sep/2023 17:16:01] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 17:16:06,683] INFO _log() L224  127.0.0.1 - - [25/Sep/2023 17:16:06] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 17:16:07,296] INFO _log() L224  127.0.0.1 - - [25/Sep/2023 17:16:07] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 17:16:34,682] INFO _log() L224  127.0.0.1 - - [25/Sep/2023 17:16:34] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 17:16:36,286] INFO _log() L224  127.0.0.1 - - [25/Sep/2023 17:16:36] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 17:16:44,895] INFO _log() L224  127.0.0.1 - - [25/Sep/2023 17:16:44] "GET /me?user=teste HTTP/1.1" 200 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 17:19:04,985] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5001
 * Running on http://192.168.15.8:5001 (Press CTRL+C to quit) - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-25 17:19:08,049] INFO _log() L224  127.0.0.1 - - [25/Sep/2023 17:19:08] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\Lucas\dev\Pos Eng Soft Puc RJ\mvp-2\user_api\env\Lib\site-packages\werkzeug\_internal.py L224 
